export const USERS_LOAD_STARTED = 'USERS_LOAD_STARTED';
export const USERS_LOAD_SUCCESS = 'USERS_LOAD_SUCCESS';
export const USERS_LOAD_FAILED = 'USERS_LOAD_FAILED';

export const USER_LOAD_STARTED = 'USER_LOAD_STARTED';
export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';
export const USER_LOAD_FAILED = 'USER_LOAD_FAILED';

export const CURRENT_USER_LOAD_STARTED = 'CURRENT_USER_LOAD_STARTED';
export const CURRENT_USER_LOAD_SUCCESS = 'CURRENT_USER_LOAD_SUCCESS';
export const CURRENT_USER_LOAD_FAILED = 'CURRENT_USER_LOAD_FAILED';

export const SIGN_IN_STARTED = 'SIGN_IN_STARTED';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

export const SIGN_UP_STARTED = 'SIGN_UP_STARTED';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';

export const SIGN_OUT_STARTED = 'SIGN_OUT_STARTED';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILED = 'SIGN_OUT_FAILED';

export const ROUTE_CHANGED = 'ROUTE_CHANGED';