export const USERS_LOAD_STARTED = 'USERS_LOAD_STARTED';
export const USERS_LOAD_SUCCESS = 'USERS_LOAD_SUCCESS';
export const USERS_LOAD_FAILED = 'USERS_LOAD_FAILED';

export const USER_LOAD_STARTED = 'USER_LOAD_STARTED';
export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';
export const USER_LOAD_FAILED = 'USER_LOAD_FAILED';
